import 'package:flutter/material.dart';
import 'services/data_export_service.dart';
const Color _exportBackground=Color(0xFF07111C);const Color _exportSurface=Color(0xFF111D2A);const Color _exportCyan=Color(0xFF43E8FF);
class DataExportPage extends StatefulWidget{const DataExportPage({super.key});@override State<DataExportPage> createState()=>_DataExportPageState();}
class _DataExportPageState extends State<DataExportPage>{final service=DataExportService.instance;String cadence='off';bool loading=true;bool exporting=false;
  @override void initState(){super.initState();_load();} Future<void> _load()async{cadence=await service.getCadence();if(mounted)setState(()=>loading=false);}
  String _label(String v)=>v=='daily'?'Every day':v=='weekly'?'Every week':v=='monthly'?'Every month':'Off';
  Future<void> _change()async{final v=await showModalBottomSheet<String>(context:context,backgroundColor:_exportSurface,builder:(c)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[for(final x in const['off','daily','weekly','monthly'])ListTile(title:Text(_label(x)),trailing:x==cadence?const Icon(Icons.check_rounded,color:_exportCyan):null,onTap:()=>Navigator.pop(c,x))])));if(v==null)return;await service.setCadence(v);if(mounted)setState(()=>cadence=v);}
  Future<void> _export()async{if(exporting)return;setState(()=>exporting=true);try{await service.exportAndShare();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Could not export data: $e')));}finally{if(mounted)setState(()=>exporting=false);}}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:_exportBackground,appBar:AppBar(backgroundColor:_exportBackground,title:const Text('Data & Export')),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(18),children:[
    Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:_exportSurface,borderRadius:BorderRadius.circular(18)),child:const Text('Exports include your profile settings, watchlist/library, watched episodes, ratings, comments, activity, following list and blocked-user list.',style:TextStyle(color:Colors.white70,height:1.45))),const SizedBox(height:16),
    ListTile(tileColor:_exportSurface,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)),leading:const Icon(Icons.download_rounded,color:_exportCyan),title:const Text('Export now'),subtitle:const Text('Create a JSON backup and choose where to save or share it.'),trailing:exporting?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.chevron_right_rounded),onTap:exporting?null:_export),const SizedBox(height:12),
    ListTile(tileColor:_exportSurface,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)),leading:const Icon(Icons.schedule_rounded,color:_exportCyan),title:const Text('Automatic backup'),subtitle:Text(cadence=='off'?'Off':'${_label(cadence)} while Chiplux is being used'),trailing:const Icon(Icons.chevron_right_rounded),onTap:_change),const SizedBox(height:12),
    const Text('Automatic backups are checked when Chiplux opens. If the interval passed while the app was closed, the backup is created the next time the app starts.',style:TextStyle(color:Colors.white38,fontSize:11,height:1.4))]));}
