// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQAqWMkhlA5mHtOg-p3h61lMNdqomoL6o',
    appId: '1:249764986412:web:805c83dce49d7fa9259b89',
    messagingSenderId: '249764986412',
    projectId: 'chiplux-c485a',
    authDomain: 'chiplux-c485a.firebaseapp.com',
    storageBucket: 'chiplux-c485a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOc5csPnw7RwdbgpODFp6WnBXwPcxOt_M',
    appId: '1:249764986412:android:4454f0584ade5f5b259b89',
    messagingSenderId: '249764986412',
    projectId: 'chiplux-c485a',
    storageBucket: 'chiplux-c485a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MKXeFnpCYS29kTQQsbyDy-lURv3OpAE',
    appId: '1:249764986412:ios:dd3484e36370deb6259b89',
    messagingSenderId: '249764986412',
    projectId: 'chiplux-c485a',
    storageBucket: 'chiplux-c485a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-MKXeFnpCYS29kTQQsbyDy-lURv3OpAE',
    appId: '1:249764986412:ios:dd3484e36370deb6259b89',
    messagingSenderId: '249764986412',
    projectId: 'chiplux-c485a',
    storageBucket: 'chiplux-c485a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQAqWMkhlA5mHtOg-p3h61lMNdqomoL6o',
    appId: '1:249764986412:web:746abb394288510e259b89',
    messagingSenderId: '249764986412',
    projectId: 'chiplux-c485a',
    authDomain: 'chiplux-c485a.firebaseapp.com',
    storageBucket: 'chiplux-c485a.firebasestorage.app',
  );
}
